package edu.liberty.bemccandless.csis505.hw6.exercise2;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author bemccandless
 */
public class HW6Exercise2 extends javax.swing.JFrame {
    
    private DataService dataService = null;
    private final List<Book> bookList = new ArrayList();
    private int currentBookIndex;
    private int bookListSize = 0;
    private boolean editMode = false;

    /**
     * Creates new form SqlDataView
     */
    public HW6Exercise2() {
        try {
            dataService = new DataService();
            initComponents();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Unable to establish connection to database", "SQL Error", JOptionPane.ERROR_MESSAGE);
            System.err.println(ex);
            System.exit(1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleTextBox = new javax.swing.JTextField();
        copyrightTextBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        isbnTextBox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        editionTextBox = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        authorList = new javax.swing.JList<Author>();
        addAuthorBtn = new javax.swing.JButton();
        editAuthorBtn = new javax.swing.JButton();
        previousBookBtn = new javax.swing.JButton();
        nextBookBtn = new javax.swing.JButton();
        currentBookTextBox = new javax.swing.JTextField();
        addBookBtn = new javax.swing.JButton();
        editBookBtn = new javax.swing.JButton();
        deleteAuthorBtn = new javax.swing.JButton();
        deleteBookBtn = new javax.swing.JButton();
        bookCancelBtn = new javax.swing.JButton();
        bookSaveBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleTextBox.setEditable(false);
        titleTextBox.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        titleTextBox.setEnabled(false);

        copyrightTextBox.setEditable(false);
        copyrightTextBox.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        copyrightTextBox.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Authors");

        jLabel3.setText("Copyright");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Books");

        jLabel5.setText("ISBN");

        isbnTextBox.setEditable(false);
        isbnTextBox.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        isbnTextBox.setEnabled(false);
        isbnTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnTextBoxActionPerformed(evt);
            }
        });

        jLabel6.setText("Edition");

        editionTextBox.setEditable(false);
        editionTextBox.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        editionTextBox.setEnabled(false);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Title");

        authorList.setModel(populateAuthorList());
        authorList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        authorList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                authorListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(authorList);

        addAuthorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/liberty/bemccandless/csis505/hw6/exercise2/resources/user-plus.png"))); // NOI18N
        addAuthorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAuthorBtnActionPerformed(evt);
            }
        });

        editAuthorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/liberty/bemccandless/csis505/hw6/exercise2/resources/pencil.png"))); // NOI18N

        previousBookBtn.setText("Previous");
        previousBookBtn.setEnabled(false);
        previousBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousBookBtnActionPerformed(evt);
            }
        });

        nextBookBtn.setText("Next");
        nextBookBtn.setEnabled(false);
        nextBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBookBtnActionPerformed(evt);
            }
        });

        currentBookTextBox.setEditable(false);
        currentBookTextBox.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        currentBookTextBox.setEnabled(false);
        currentBookTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentBookTextBoxActionPerformed(evt);
            }
        });

        addBookBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/liberty/bemccandless/csis505/hw6/exercise2/resources/plus.png"))); // NOI18N
        addBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookBtnActionPerformed(evt);
            }
        });

        editBookBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/liberty/bemccandless/csis505/hw6/exercise2/resources/pencil.png"))); // NOI18N
        editBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBookBtnActionPerformed(evt);
            }
        });

        deleteAuthorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/liberty/bemccandless/csis505/hw6/exercise2/resources/user-minus.png"))); // NOI18N

        deleteBookBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/liberty/bemccandless/csis505/hw6/exercise2/resources/trashcan.png"))); // NOI18N
        deleteBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBookBtnActionPerformed(evt);
            }
        });

        bookCancelBtn.setText("Cancel");
        bookCancelBtn.setEnabled(false);
        bookCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookCancelBtnActionPerformed(evt);
            }
        });

        bookSaveBtn.setText("Save");
        bookSaveBtn.setEnabled(false);
        bookSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookSaveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addAuthorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editAuthorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteAuthorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(addBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(isbnTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(copyrightTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editionTextBox))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(titleTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(previousBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(currentBookTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nextBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bookSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bookCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(deleteBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(titleTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(isbnTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(copyrightTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(editionTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(previousBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nextBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(currentBookTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(addBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bookCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(editAuthorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(deleteAuthorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(addAuthorBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void previousBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousBookBtnActionPerformed
        currentBookIndex--;
      
        if (currentBookIndex < 0) {
           currentBookIndex = bookListSize - 1;
        }

        currentBookTextBoxActionPerformed(evt);  
    }//GEN-LAST:event_previousBookBtnActionPerformed

    private void addAuthorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAuthorBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addAuthorBtnActionPerformed

    private void addBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookBtnActionPerformed
        clearBookTextBoxes();
        isbnTextBox.setEditable(true);
        isbnTextBox.setEnabled(true);
        setBookTextBoxEnabled(true);
    }//GEN-LAST:event_addBookBtnActionPerformed

    private void clearBookTextBoxes() {
        titleTextBox.setText("");
        copyrightTextBox.setText("");
        editionTextBox.setText("");
        isbnTextBox.setText("");
        currentBookTextBox.setText("");
    }
    
    private void isbnTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbnTextBoxActionPerformed

    private void authorListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_authorListValueChanged
        previousBookBtn.setEnabled(true);
        nextBookBtn.setEnabled(true);
        
        Author author = authorList.getSelectedValue();
        try {
            bookList.clear();
            ResultSet books = dataService.selectBooksByAuthor(author.getAuthorID());
            
            while (books.next()) {
                Book book = new Book();
                book.setTitle(books.getString("title"));
                book.setIsbn(books.getString("isbn"));
                book.setEditionNumber(books.getInt("editionNumber"));
                book.setCopyright(books.getString("copyright"));
                
                bookList.add(book);
            }
            
            if (bookList.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "No records found.", "Books", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            if (evt != null) {
                currentBookIndex = 0;
            }
            bookListSize = bookList.size();
            
            currentBookTextBoxActionPerformed(null);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(
                    rootPane, "Unable to get list of books.", "SQL Error", JOptionPane.ERROR_MESSAGE);
            System.err.println(ex);
        }
    }//GEN-LAST:event_authorListValueChanged

    private void nextBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBookBtnActionPerformed
        currentBookIndex++;
      
        if (currentBookIndex >= bookListSize) {
           currentBookIndex = 0;
        }

        currentBookTextBoxActionPerformed(evt);
    }//GEN-LAST:event_nextBookBtnActionPerformed

    private void currentBookTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentBookTextBoxActionPerformed
        Book book = bookList.get(currentBookIndex);
        
        titleTextBox.setText(book.getTitle());
        isbnTextBox.setText(book.getIsbn());
        copyrightTextBox.setText(book.getCopyright());
        editionTextBox.setText(String.valueOf(book.getEditionNumber()));
        
        currentBookTextBox.setText(String.format("%d / %d", currentBookIndex + 1, bookListSize));
    }//GEN-LAST:event_currentBookTextBoxActionPerformed

    private void editBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBookBtnActionPerformed
        editMode = true;
        setBookTextBoxEnabled(true);
    }//GEN-LAST:event_editBookBtnActionPerformed

    private void bookSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookSaveBtnActionPerformed
        setBookTextBoxEnabled(false);
        try {
            if (editMode) {
                Book book = bookList.get(currentBookIndex);
                book.setTitle(titleTextBox.getText());
                book.setIsbn(isbnTextBox.getText());
                book.setCopyright(copyrightTextBox.getText());
                book.setEditionNumber(Integer.valueOf(editionTextBox.getText()));

                dataService.updateBook(book);
                bookList.add(book);
                editMode = false;
            } else {
                Book book = new Book();
                book.setTitle(titleTextBox.getText());
                book.setIsbn(isbnTextBox.getText());
                book.setCopyright(copyrightTextBox.getText());
                book.setEditionNumber(Integer.valueOf(editionTextBox.getText()));

                dataService.addBookForAuthor(book, authorList.getSelectedValue().getAuthorID());
                
                currentBookIndex = bookList.size();
            }
            
            authorListValueChanged(null);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, "Edition must be an integer value.", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
            setBookTextBoxEnabled(true);
            editionTextBox.requestFocus();
            editionTextBox.selectAll();
            System.err.println(ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Unable to save record.", "SQL Error", JOptionPane.ERROR_MESSAGE);
            setBookTextBoxEnabled(true);
            System.err.println(ex);
        }
    }//GEN-LAST:event_bookSaveBtnActionPerformed

    private void bookCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookCancelBtnActionPerformed
        setBookTextBoxEnabled(false);
        authorListValueChanged(null);
    }//GEN-LAST:event_bookCancelBtnActionPerformed

    private void deleteBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBookBtnActionPerformed
        try {
            String isbn = bookList.get(currentBookIndex).getIsbn();
            int authorId = authorList.getSelectedValue().getAuthorID();
            
            dataService.deleteBookForAuthor(isbn, authorId);
            currentBookIndex = 0;
            authorListValueChanged(null);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(
                    rootPane, "Unable to delete book.", "SQL Error", JOptionPane.ERROR_MESSAGE);
            System.err.println(ex);
        }
    }//GEN-LAST:event_deleteBookBtnActionPerformed
    
    private void setBookTextBoxEnabled(boolean value) {
        authorList.setEnabled(!value);
        
        titleTextBox.setEditable(value);
        copyrightTextBox.setEditable(value);
        editionTextBox.setEditable(value);
        
        titleTextBox.setEnabled(value);
        copyrightTextBox.setEnabled(value);
        editionTextBox.setEnabled(value);
        
        bookSaveBtn.setEnabled(value);
        bookCancelBtn.setEnabled(value);
        nextBookBtn.setEnabled(!value);
        previousBookBtn.setEnabled(!value);
    }
    
    private ListModel<Author> populateAuthorList() {
        DefaultListModel listModel = new DefaultListModel();
        try {
            ResultSet authors = dataService.selectAllAuthors();
            while (authors.next()) {
                Author author = new Author();
                author.setAuthorID(authors.getInt("authorID"));
                author.setFirstName(authors.getString("firstName"));
                author.setLastName(authors.getString("lastName"));
                
                listModel.addElement(author);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(
                    rootPane, "Unable to get list of authors.", "SQL Error", JOptionPane.ERROR_MESSAGE);
            System.err.println(ex);
        }
        
        return listModel;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HW6Exercise2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HW6Exercise2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HW6Exercise2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HW6Exercise2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HW6Exercise2 form = new HW6Exercise2();
                form.setTitle("Book Catalog");
                form.setResizable(false);
                form.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAuthorBtn;
    private javax.swing.JButton addBookBtn;
    private javax.swing.JList<Author> authorList;
    private javax.swing.JButton bookCancelBtn;
    private javax.swing.JButton bookSaveBtn;
    private javax.swing.JTextField copyrightTextBox;
    private javax.swing.JTextField currentBookTextBox;
    private javax.swing.JButton deleteAuthorBtn;
    private javax.swing.JButton deleteBookBtn;
    private javax.swing.JButton editAuthorBtn;
    private javax.swing.JButton editBookBtn;
    private javax.swing.JTextField editionTextBox;
    private javax.swing.JTextField isbnTextBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextBookBtn;
    private javax.swing.JButton previousBookBtn;
    private javax.swing.JTextField titleTextBox;
    // End of variables declaration//GEN-END:variables
}
